### ISSUE TITLE
Pros and cons of using shell instead of execline

### ISSUE THREAD

**Issue by firasuke** [dslm4515/MLFS-S6-Bootscripts#13]
Hey there,

I noticed that you recently moved away from `execline` and rewrote your bootscripts in shell.

If I may ask:
- Why did you do that?
- Is it for the sake of simplicity?
- Are you planning on removing `execline`?
- Have you noticed any real benefits?

Good luck with your endeavours!

**Comment by dslm4515** [comment]
> Why did you do that?

I find it difficult to script in execline. I can write scripts faster in shell. If I have a new idea for a service, it takes me a lot longer to develop an execline script. I might consider going back once I've mastered it. Lot of my execline scripts seemed to work but i have a very small understanding on why it works.

> Is it for the sake of simplicity?

Some of  my shell scripts are shorter than in execline. I can't remember specific examples. Plus, i would not need to know another shell language.

> Are you planning on removing `execline` ?

I tried. Turns out I can use shell scripts for oneshots services but not longrun services. It would be nice to have on less package to build for my boot scripts. I think S6 requires execline to be installed.

> Have you noticed any real benefits? 

It became easier to develop and redesign my boot scripts. If I made a typoe or want to tweak a script, no need to re-compile the database... of course, there are tools to modify the boot database without re-compiling it.... I haven't gotten to designing scripts to automate that. So far, my bootscripts are based on Obarun: Essentially Read-only & Read-Write stages of boot. Speed-wise? No difference so far.
